// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3r52sxAczBectb_LxVy6nEdKLd7oxPM',
    appId: '1:953354017947:web:17b3b8090daed9e618ba3e',
    messagingSenderId: '953354017947',
    projectId: 'chat-master-101b2',
    authDomain: 'chat-master-101b2.firebaseapp.com',
    storageBucket: 'chat-master-101b2.appspot.com',
    measurementId: 'G-5XQ9F8M56P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9aGDMhsGNE_4C6S9Z4XYVIVaf5ZIlN8',
    appId: '1:953354017947:android:4bee3218b84c041818ba3e',
    messagingSenderId: '953354017947',
    projectId: 'chat-master-101b2',
    storageBucket: 'chat-master-101b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVtbTMAtkN3XtB-H3HhsAYq1itXTDS97M',
    appId: '1:953354017947:ios:371b811f4473f67218ba3e',
    messagingSenderId: '953354017947',
    projectId: 'chat-master-101b2',
    storageBucket: 'chat-master-101b2.appspot.com',
    iosBundleId: 'com.example.chatMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVtbTMAtkN3XtB-H3HhsAYq1itXTDS97M',
    appId: '1:953354017947:ios:759b2e36fb0c315518ba3e',
    messagingSenderId: '953354017947',
    projectId: 'chat-master-101b2',
    storageBucket: 'chat-master-101b2.appspot.com',
    iosBundleId: 'com.example.chatMaster.RunnerTests',
  );
}
